#define CONFIG_VENDOR_SHORT "Soliton"
#define CONFIG_VENDOR_LONG "Soliton Network Systems (Shanghai) Co., Ltd"
#define CONFIG_PRODUCT_SHORT "authbox"
#define CONFIG_PRODUCT_LONG "Soliton Authentication Box"

#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_BN 1
#define CONFIG_CRYPTO_ERR 1
#define CONFIG_CRYPTO_BIO 1
#define CONFIG_CRYPTO_LHASH 1

#define CONFIG_CRYPTO_MD4 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_RIPEMD 1
#define CONFIG_CRYPTO_SHA 1
#define CONFIG_CRYPTO_SHA0 1
#define CONFIG_CRYPTO_SHA1 1
#define CONFIG_CRYPTO_SHA256 1
#define CONFIG_CRYPTO_SHA512 1
#define CONFIG_CRYPTO_DES 1
#define CONFIG_CRYPTO_DES_CBCM 1
#define CONFIG_CRYPTO_BF 1
#define CONFIG_CRYPTO_AES 1
#define CONFIG_CRYPTO_IDEA 1
#define CONFIG_CRYPTO_CAST 1
#define CONFIG_CRYPTO_RC2 1
#define CONFIG_CRYPTO_RC4 1
#define CONFIG_CRYPTO_RC5 1

#define CONFIG_CRYPTO_HMAC 1

#define CONFIG_CRYPTO_RSA 1
#define CONFIG_CRYPTO_DSA 1
#define CONFIG_CRYPTO_DH 1

#define CONFIG_CRYPTO_COMP 1
#define CONFIG_CRYPTO_OCSP 1

#define CONFIG_CRYPTO_APPLINK 1

#define CONFIG_ETHER_UNIT 2
#define CONFIG_PPP_UNITS 8

#define CONFIG_INET 1
#define CONFIG_INET_TCP 1
#define CONFIG_INET_UDP 1
#define CONFIG_INET_ICMP 1

#define CONFIG_DNS 1
#define CONFIG_DNS_EXIST 1

#define CONFIG_VLAN 1
#define CONFIG_VLAN_GROUP 8

#define CONFIG_BRIDGE 1
#define CONFIG_BRIDGE_DEVICES 2

#define CONFIG_L2TP 1
#define CONFIG_L2TP_LAC 1
#define CONFIG_L2TP_LNS 1

#define CONFIG_PPP 1
#define CONFIG_PPP_IPCP 1
#define CONFIG_PPP_LQR 1
#define CONFIG_PPP_CCP 1
#define CONFIG_PPP_CBCP 1
#define CONFIG_PPP_CHAP 1
#define CONFIG_PPP_EAP 1
#define CONFIG_PPP_PAP 1
#undef CONFIG_PPP_MP
#undef CONFIG_PPP_BCP

#define CONFIG_PPP_L2TP 1
#define CONFIG_PPP_PPPOE 1

#define CONFIG_PPP_MD5 1
#define CONFIG_PPP_MSCHAP 1
#define CONFIG_PPP_MSCHAPV2 1
#define CONFIG_PPP_MPPCE 1

#define CONFIG_HTTP 1
#define CONFIG_HTTP_DEFLATE 1
#define CONFIG_HTTP_CHUNKED 1

#define CONFIG_ZLIB 1
#define CONFIG_HTML 1
#define CONFIG_HTML_FORM 1
#define CONFIG_GIF 1

#define CONFIG_SECRET_PLAIN 1
#define CONFIG_SECRET_FILE 1

#define CONFIG_CHAP 1
#define CONFIG_MSCHAP 1
#define CONFIG_MSCHAPV2 1
#define CONFIG_MPPE 1

#define CONFIG_EAP 1
#define CONFIG_EAP_MD5 1
#define CONFIG_EAP_MSCHAPV2 1
#define CONFIG_EAP_TLS 1
#undef CONFIG_EAP_PEAP

#define CONFIG_DHCP 1
#define CONFIG_DHCP_PCAP 1
#define CONFIG_DHCP_CLIENT 1
#define CONFIG_DHCP_SERVER 1

#define CONFIG_PPPOE 1
#define CONFIG_PPPOE_PCAP 1
#define CONFIG_PPPOE_SERVER 1
#define CONFIG_PPPOE_CLIENT 1

#define CONFIG_ISAKMP 1
#define CONFIG_ISAKMP_NATT 1
#define CONFIG_ISAKMP_IDENT 1
#define CONFIG_ISAKMP_AGG 1
#define CONFIG_ISAKMP_BASE 1
#define CONFIG_ISAKMP_INFO 1
#define CONFIG_ISAKMP_AUTH 1
#define CONFIG_ISAKMP_DOI 1

#define CONFIG_IPSEC 1
#define CONFIG_IPSEC_DOI 1

#define CONFIG_IKE 1
#define CONFIG_IKE_MAIN 1
#define CONFIG_IKE_AGG 1
#define CONFIG_IKE_QUICK 1
#define CONFIG_IKE_NEWGRP 1

#define CONFIG_SYSLOG 1
#define CONFIG_SYSLOG_TIMESTAMP 1
#undef CONFIG_SYSLOG_HOSTNAME
#define CONFIG_SYSLOG_TAG 1

#define CONFIG_LOG 1
#define CONFIG_LOG_SEVERITY 1
#undef CONFIG_LOG_TIMESTAMP

#define CONFIG_LOG_KMSG 1
#define CONFIG_LOG_KMSG_DEV 1
#define CONFIG_LOG_KMSG_LEVEL 4

#define CONFIG_CLI 1
#define CONFIG_CLI_HISTORY 1

#define CONFIG_CLI_STDIO 1

#define CONFIG_USB 1
#define CONFIG_CCID 1
#define CONFIG_PCSC 1
#define CONFIG_SCARD 1
//#define CONFIG_PKCS15 1

#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437 1
#define CONFIG_NLS_CODEPAGE_932 1
#define CONFIG_NLS_CODEPAGE_936 1
#define CONFIG_NLS_CODEPAGE_950 1
#define CONFIG_NLS_ISO8859_1 1
#define CONFIG_NLS_ASCII 1
#define CONFIG_NLS_UTF8 1

#define CONFIG_NETLINK 1
#define CONFIG_PACKET 1
#define CONFIG_KEY 1