#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_BN 1
#define CONFIG_CRYPTO_ERR 1
#define CONFIG_CRYPTO_BIO 1
#define CONFIG_CRYPTO_FP 1
#define CONFIG_CRYPTO_LHASH 1

#define CONFIG_CRYPTO_MD4 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_RIPEMD 1
#define CONFIG_CRYPTO_SHA 1
#define CONFIG_CRYPTO_SHA0 1
#define CONFIG_CRYPTO_SHA1 1
#define CONFIG_CRYPTO_SHA256 1
#define CONFIG_CRYPTO_SHA512 1
#define CONFIG_CRYPTO_DES 1
#define CONFIG_CRYPTO_DES_CBCM 1
#define CONFIG_CRYPTO_BF 1
#define CONFIG_CRYPTO_AES 1
#define CONFIG_CRYPTO_IDEA 1
#define CONFIG_CRYPTO_CAST 1
#define CONFIG_CRYPTO_RC2 1
#define CONFIG_CRYPTO_RC4 1
#define CONFIG_CRYPTO_RC5 1

#define CONFIG_CRYPTO_HMAC 1

#define CONFIG_CRYPTO_RSA 1
#define CONFIG_CRYPTO_DSA 1
#define CONFIG_CRYPTO_DH 1

#define CONFIG_CRYPTO_COMP 1
#define CONFIG_CRYPTO_OCSP 1

#define CONFIG_CRYPTO_APPLINK 1
#define CONFIG_BIO_SOCK 1

#define CONFIG_ZLIB 1
